#!/usr/bin/env bash
# Render the shared palette into each tool's color config.
# Source of truth:  theme/colors.sh
# Usage:            make theme   (or run this script directly)

set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../theme/colors.sh
source "$DOTFILES/theme/colors.sh"

BANNER="# AUTO-GENERATED by scripts/apply-theme.sh — edit theme/colors.sh instead"
LUA_BANNER="-- AUTO-GENERATED by scripts/apply-theme.sh — edit theme/colors.sh instead"

# ---------------------------------------------------------------------------
# 1. nvim — emit a Lua palette table that colors.lua requires
# ---------------------------------------------------------------------------
mkdir -p "$DOTFILES/nvim/.config/nvim/lua/custom"
cat > "$DOTFILES/nvim/.config/nvim/lua/custom/palette.lua" <<EOF
$LUA_BANNER
return {
  bg              = "$THEME_BG",
  bg_dark         = "$THEME_BG_DARK",
  bg_float        = "$THEME_BG_FLOAT",
  bg_highlight    = "$THEME_BG_HIGHLIGHT",
  bg_select       = "$THEME_BG_SELECT",
  fg              = "$THEME_FG",
  fg_dark         = "$THEME_FG_DARK",
  comment         = "$THEME_COMMENT",
  gutter          = "$THEME_GUTTER",
  blue            = "$THEME_BLUE",
  cyan            = "$THEME_CYAN",
  teal            = "$THEME_TEAL",
  magenta         = "$THEME_MAGENTA",
  purple          = "$THEME_PURPLE",
  string          = "$THEME_STRING",
  variable        = "$THEME_VARIABLE",
  number          = "$THEME_NUMBER",
  red             = "$THEME_RED",
}
EOF

# ---------------------------------------------------------------------------
# 2. lazygit — single config.yml (no include support)
# ---------------------------------------------------------------------------
cat > "$DOTFILES/lazygit/.config/lazygit/config.yml" <<EOF
$BANNER
gui:
  theme:
    activeBorderColor:
      - "$THEME_CYAN"
      - bold
    inactiveBorderColor:
      - "$THEME_COMMENT"
    optionsTextColor:
      - "$THEME_BLUE"
    selectedLineBgColor:
      - "$THEME_BG_HIGHLIGHT"
    selectedRangeBgColor:
      - "$THEME_BG_HIGHLIGHT"
    cherryPickedCommitBgColor:
      - "$THEME_BG_SELECT"
    cherryPickedCommitFgColor:
      - "$THEME_PURPLE"
    markedBaseCommitBgColor:
      - "$THEME_BG_SELECT"
    markedBaseCommitFgColor:
      - "$THEME_MAGENTA"
    unstagedChangesColor:
      - "$THEME_RED"
    defaultFgColor:
      - "$THEME_FG"
    searchingActiveBorderColor:
      - "$THEME_CYAN"
  authorColors:
    "*": "$THEME_BLUE"
  branchColors:
    main: "$THEME_PURPLE"
    master: "$THEME_PURPLE"
EOF

# ---------------------------------------------------------------------------
# 3. kitty — current-theme.conf (kitty.conf already `include`s it)
# ---------------------------------------------------------------------------
cat > "$DOTFILES/kitty/.config/kitty/current-theme.conf" <<EOF
$BANNER

foreground              $THEME_FG
background              $THEME_BG
selection_foreground    $THEME_FG
selection_background    $THEME_BG_SELECT

cursor                  $THEME_FG
cursor_text_color       $THEME_BG

url_color               $THEME_CYAN

active_tab_foreground   $THEME_BG
active_tab_background   $THEME_FG
inactive_tab_foreground $THEME_COMMENT
inactive_tab_background $THEME_BG_FLOAT

# Normal colors (0-7)
color0                  $THEME_BG
color1                  $THEME_RED
color2                  $THEME_TEAL
color3                  $THEME_PURPLE
color4                  $THEME_BLUE
color5                  $THEME_MAGENTA
color6                  $THEME_CYAN
color7                  $THEME_FG

# Bright colors (8-15)
color8                  $THEME_COMMENT
color9                  $THEME_RED
color10                 $THEME_TEAL
color11                 $THEME_VARIABLE
color12                 $THEME_BLUE
color13                 $THEME_MAGENTA
color14                 $THEME_CYAN
color15                 $THEME_FG
EOF

# ---------------------------------------------------------------------------
# 4. zellij — rewrite only the `themes { ... }` block in config.kdl,
#    preserving keybinds and everything else.
# ---------------------------------------------------------------------------
ZELLIJ_CONF="$DOTFILES/zellij/.config/zellij/config.kdl"
ZELLIJ_THEME_BLOCK=$(cat <<EOF
themes {
    // $BANNER
    default {
        bg "$THEME_BG_FLOAT"
        fg "$THEME_FG"
        red "$THEME_RED"
        green "$THEME_TEAL"
        blue "$THEME_BLUE"
        yellow "$THEME_PURPLE"
        magenta "$THEME_MAGENTA"
        orange "$THEME_VARIABLE"
        cyan "$THEME_CYAN"
        black "$THEME_BG"
        white "$THEME_FG"
    }
}
EOF
)

# Strip the existing themes block (line starting with "themes {" through its
# matching "}") and append the freshly rendered one.
python3 - "$ZELLIJ_CONF" <<PY
import re, sys, pathlib
path = pathlib.Path(sys.argv[1])
src = path.read_text()
# Remove any existing themes { ... } block (balanced braces).
def strip_block(text):
    i = text.find("themes {")
    if i < 0:
        return text.rstrip() + "\n"
    depth = 0
    j = i
    while j < len(text):
        c = text[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                j += 1
                break
        j += 1
    return (text[:i].rstrip() + "\n" + text[j:].lstrip()).rstrip() + "\n"
new = strip_block(src).rstrip() + "\n\n" + """$ZELLIJ_THEME_BLOCK""" + "\n"
path.write_text(new)
PY

echo "Theme applied:"
echo "  nvim    → nvim/.config/nvim/lua/custom/palette.lua"
echo "  lazygit → lazygit/.config/lazygit/config.yml"
echo "  kitty   → kitty/.config/kitty/current-theme.conf"
echo "  zellij  → zellij/.config/zellij/config.kdl (themes block)"
echo
echo "Reload notes:"
echo "  - kitty:   ctrl+shift+F5  (or restart)"
echo "  - nvim:    :Lazy reload tokyonight.nvim"
echo "  - zellij:  detach + re-attach, or restart session"
echo "  - lazygit: quit and reopen"
